eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8887/eureka/
server:
    port: 8003
spring:
    application:
        name: service-zuul
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: service-feign