eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.25.12:8887/eureka/
server:
    port: 8904
spring:
    application:
        name: service-zuul
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: service-feign