server:
   port: 8002

#eureka:
#   client:
#      serviceUrl:
#        defaultZone: http://192.168.25.12:8887/eureka/
#spring:
#   application:
#      name: service-feign
#
#feign.httpclient.enabled: true
#feign:
#   hystrix:
#     enabled: true
#因为增加了apollo，所以去掉上面内容
app.id: feign-client
apollo.meta: http://192.168.25.111:8080